const SET_STUDENTS = 'SET_STUDENTS';
const SET_SCHOOLS = 'SET_SCHOOLS';
const DESTROY_STUDENT = 'DESTROY_STUDENT';
const CREATE_STUDENT = 'CREATE_STUDENT';
export {
  SET_STUDENTS,
  SET_SCHOOLS,
  DESTROY_STUDENT,
  CREATE_STUDENT
}
